# Dependabot config file
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "dependabot[bot]"
      - "dependabot-preview[bot]"
      - "dependabot"
    default_assignees:
      - "dependabot[bot]"
      - "dependabot-preview[bot]"
      - "dependabot"
    default_labels:
      - "dependencies"
      - "automerge"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    ignored_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "dependabot[bot]"
      - "dependabot-preview[bot]"
      - "dependabot"
    default_assignees:
      - "dependabot[bot]"
      - "dependabot-preview[bot]"
      - "dependabot"
    default_labels:
      - "dependencies"
      - "automerge"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    ignored_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "dependabot[bot]"
      - "dependabot-preview[bot]"
      - "dependabot"
    default_assignees:
      - "dependabot[bot]"
      - "dependabot-preview[bot]"
      - "dependabot"
    default_labels:
      - "dependencies"
      - "automerge"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    ignored_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "dependabot[bot]"
      - "dependabot-preview[bot]"
      - "dependabot"
    default_assignees:
      - "dependabot[bot]"
      - "dependabot-preview[bot]"
      - "dependabot"
    default_labels:
      - "dependencies"
      - "automerge"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    ignored_updates:
      - match:
          dependency_type: "all"
          update_type: "all"